Gc 64 home page
catalyzt-tech/OP-GPT pull request #1
Opened 2024-09-01 16:21 UTC by TGRZiminiar

# Description

[//]: # "Please include a summary of the changes and the related issue. (You can write below without deleting this comment)"

### What
[//]: # "Briefly describe this feature / fix / refactor (You can write below without deleting this comment)"

### Why
[//]: # "Describe the reason why we need this feature / fix / refactor or refer to Jira Ticket (You can write below without deleting this comment)"

## Type of change

Please check the relevent option with `x`.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if needed)
- [X] My changes generate no new warnings
- [X] I have tested on my `Local Machine`

2024-09-01 17:04 UTC, Billy19191 requested changes
Left some comments and also follow rabbit bot suggest

2024-09-01 17:04 UTC, Billy19191 commented on app/Cpage.tsx
> +    }
Is "isLoading" unused? @TGRZiminiar

2024-09-01 17:04 UTC, Billy19191 commented on app/Cpage.tsx
> +    }
Also, remove this draft

2024-09-01 17:04 UTC, Billy19191 commented on app/[id]/page.tsx
> +}
Delete this 
```suggestion

```

2024-09-01 17:04 UTC, Billy19191 commented on provider/globalContext.tsx
> +  async function LoadData() {
Is this function active?

2024-09-02 05:18 UTC, TGRZiminiar commented on app/_component/sidebar-home.tsx
> +    window.location.reload();
since router.reload() doesn't work as expected, so I prefer window.location.reload

2024-09-02 05:20 UTC, TGRZiminiar commented on provider/globalContext.tsx
> +  async function LoadData() {
Just prepare the code just in case.

2024-09-02 05:21 UTC, TGRZiminiar commented on app/_component/conversation.tsx
> +];
Since we will change the text later so just keep it like this just fine for now

2024-09-02 05:27 UTC, TGRZiminiar commented on components/sidebar.tsx
> +        }
Since it from nextui docs follow the docs might be more better

2024-09-02 05:28 UTC, TGRZiminiar commented on provider/globalContext.tsx
> +  })
It just a test data it doesn't matter for now

2024-09-02 05:34 UTC, TGRZiminiar commented on app/Cpage.tsx
> +    }
It use on the function handleFetchAiAPI()

2024-09-02 05:50 UTC, Billy19191 approved these changes

2024-09-02 05:51 UTC, Billy19191 commented
Look good to me now 🤘

2024-09-02 06:15 UTC, merged